version: '2.3'

services:
  gogs:
    restart: unless-stopped
    image: gogs/gogs:0.11.43
    volumes:
      - gogs-data:/data
    container_name: gogs
    labels:
      - "traefik.frontend.rule=Host:gogs.${MYDOMAIN}"
    expose:
      - 3000
      - 2222
    ports:
      - "3000:3000"
      - "2222:2222"
    extra_hosts:
      - local:172.17.0.1
    networks:
      - service


volumes:
  gogs-data:
      driver: nfs
      driver_opts: 
        share: 172.17.0.1/srv/data/volumes/gogs

networks:
  service:
    external:
      name: service
